FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies including development dependencies
RUN npm install

# Command to run the application in development mode
CMD ["npm", "run", "dev"]