// src/tests/integration/endpoints/nfc-verification-url.test.ts
import request from 'supertest';
import app from '../../../app';
import { setupTestMocks, teardownTestMocks } from '../../test-helpers/mock-setup';
import { NfcUrlParser } from '../../test-helpers/nfc-url-parser';

/**
 * Integration tests simulating real-world URL parsing and verification
 * for NFC tags using actual URL formats that would be generated by
 * an NFC scan
 */
describe('NFC URL Verification Integration Tests', () => {
    const apiKey = 'test-api-key-123456789012345678901234567890';

    // Execute precise test setup procedures
    beforeAll(() => {
        setupTestMocks();
    });

    // Execute test cleanup to prevent cross-test contamination
    afterAll(() => {
        teardownTestMocks();
    });

    describe('URL Parameter Parsing and Verification', () => {
        /**
         * Executes systematic tests for each specific NFC tag format
         * using a data-driven test approach to ensure all tag variants
         * are correctly processed
         */
        test.each(NfcUrlParser.getStandardTestCases())(
            '$name URL verification',
            async ({ url, expectedTagId, expectedTagType }) => {
                // Convert URL to SUM message format
                const sumMessage = NfcUrlParser.urlToSumMessage(url);

                // Execute verification request
                const response = await request(app)
                    .post('/api/nfc/verify')
                    .set('X-API-Key', apiKey)
                    .send({ sumMessage });

                // Validate response structure and content
                expect(response.status).toBe(200);
                expect(response.body.success).toBe(true);
                expect(response.body.data.tagId).toEqual(expectedTagId);
                expect(response.body.data.metadata.tagType).toEqual(expectedTagType);

                // Validate metadata contains expected fields
                expect(response.body.data.metadata).toHaveProperty('redirectUrl');
                expect(response.body.data.metadata.redirectUrl).toMatch(/^https?:\/\//);

                // Validate timestamps
                expect(response.body.timestamp).toBeDefined();
                expect(new Date(response.body.timestamp)).toBeInstanceOf(Date);
                expect(new Date(response.body.data.verifiedAt)).toBeInstanceOf(Date);
            }
        );

        /**
         * Tests parsing of the complete URL as input
         * This simulates receiving the entire URL that would be generated
         * when a mobile device scans an NFC tag
         */
        it('parses and processes complete URL as sumMessage.data', async () => {
            // Complete URL that would be produced by scanning an NFC tag
            const completeUrl = 'https://adaki.me/v?picc=E2347894F792312B&cmac=D3A2910582F48A15&uid=041E3C8A556480';

            const requestBody = {
                sumMessage: {
                    type: 'tag',
                    data: completeUrl
                }
            };

            const response = await request(app)
                .post('/api/nfc/verify')
                .set('X-API-Key', apiKey)
                .send(requestBody);

            expect(response.status).toBe(200);
            expect(response.body.success).toBe(true);
            expect(response.body.data.isValid).toBe(true);
            expect(response.body.data.tagId).toEqual('ntag424-e2347894');
        });
    });

    describe('Geolocation Processing', () => {
        /**
         * Verifies correct handling of geolocation data with NFC verification
         * This simulates a mobile device providing location context with the scan
         */
        it('processes geolocation data with NFC verification', async () => {
            // Standard URL parameters used in a real scan
            const tagParams = {
                picc: 'E2347894F792312B',
                cmac: 'D3A2910582F48A15',
                uid: '041E3C8A556480'
            };

            // Generate test request with geolocation
            const requestWithLocation = NfcUrlParser.generateTestRequest(tagParams, true);

            const response = await request(app)
                .post('/api/nfc/verify')
                .set('X-API-Key', apiKey)
                .send(requestWithLocation);

            expect(response.status).toBe(200);
            expect(response.body.success).toBe(true);

            // Log the original request and response for documentation
            console.log('Request payload:', JSON.stringify(requestWithLocation, null, 2));
            console.log('Sample response:', JSON.stringify({
                ...response.body,
                // Add sample fields for documentation
                sampleFields: {
                    data: {
                        redirectUrl: 'This field would contain the URL to redirect the user to',
                        tagId: 'Unique identifier for the verified tag',
                        metadata: {
                            tagType: 'Type of the NFC tag (NTAG 424 DNA, TagTamper, etc.)',
                            scanMethod: 'Method used for verification (SDMMAC, SDMENCFileData)',
                            readCounter: 'Number of times the tag has been read',
                            geoLocation: 'Optional geolocation data from the scanning device'
                        }
                    }
                }
            }, null, 2));
        });
    });

    describe('Real-World Scan Simulation', () => {
        /**
         * Executes a sequence of tests that simulate a complete
         * user interaction flow scanning the same tag multiple times
         */
        it('simulates a complete tag verification lifecycle', async () => {
            // Simulate first scan of tag
            const firstScanUrl = 'https://adaki.me/v?picc=E2347894F792312B&cmac=D3A2910582F48A15&uid=041E3C8A556480';

            const firstScanRequest = {
                sumMessage: NfcUrlParser.urlToSumMessage(firstScanUrl)
            };

            const firstResponse = await request(app)
                .post('/api/nfc/verify')
                .set('X-API-Key', apiKey)
                .send(firstScanRequest);

            expect(firstResponse.status).toBe(200);
            expect(firstResponse.body.success).toBe(true);
            expect(firstResponse.body.data.tagId).toEqual('ntag424-e2347894');

            // Get statistics for the tag
            const statsResponse = await request(app)
                .get('/api/nfc/stats/ntag424-e2347894')
                .set('X-API-Key', apiKey);

            expect(statsResponse.status).toBe(200);
            expect(statsResponse.body.success).toBe(true);
            expect(statsResponse.body.data.tag_id).toEqual('ntag424-e2347894');
            expect(statsResponse.body.data.verification_count).toBeGreaterThan(0);

            // Update tag configuration
            const configUpdateResponse = await request(app)
                .put('/api/nfc/config/ntag424-e2347894')
                .set('X-API-Key', apiKey)
                .send({
                    redirectUrl: 'https://adaki.io/updated-campaign',
                    isActive: true
                });

            expect(configUpdateResponse.status).toBe(200);
            expect(configUpdateResponse.body.success).toBe(true);
            expect(configUpdateResponse.body.data.redirect_url).toEqual('https://adaki.io/updated-campaign');

            // Simulate second scan with geolocation
            const secondScanRequest = {
                sumMessage: NfcUrlParser.urlToSumMessage(firstScanUrl),
                geoLocation: {
                    latitude: 40.7128,
                    longitude: -74.0060
                }
            };

            const secondResponse = await request(app)
                .post('/api/nfc/verify')
                .set('X-API-Key', apiKey)
                .send(secondScanRequest);

            expect(secondResponse.status).toBe(200);
            expect(secondResponse.body.success).toBe(true);
            expect(secondResponse.body.data.tagId).toEqual('ntag424-e2347894');
        });
    });

    describe('Error Handling for Real-World Scenarios', () => {
        /**
         * Tests error handling for invalid scan data
         */
        it('handles malformed URL parameters', async () => {
            const malformedUrl = 'https://adaki.me/v?picc=INVALID&cmac=INVALID';

            const requestBody = {
                sumMessage: NfcUrlParser.urlToSumMessage(malformedUrl)
            };

            const response = await request(app)
                .post('/api/nfc/verify')
                .set('X-API-Key', apiKey)
                .send(requestBody);

            expect(response.status).toBe(401);
            expect(response.body.success).toBe(false);
            expect(response.body.error.code).toBe('VERIFICATION_FAILED');
        });

        /**
         * Tests invalid API key handling
         */
        it('handles invalid API key', async () => {
            const validUrl = 'https://adaki.me/v?picc=E2347894F792312B&cmac=D3A2910582F48A15&uid=041E3C8A556480';

            const requestBody = {
                sumMessage: NfcUrlParser.urlToSumMessage(validUrl)
            };

            const response = await request(app)
                .post('/api/nfc/verify')
                .set('X-API-Key', 'invalid-api-key')
                .send(requestBody);

            expect(response.status).toBe(401);
            expect(response.body.success).toBe(false);
            expect(response.body.error.code).toBe('INVALID_API_KEY');
        });
    });
});