// src/tests/test-helpers/nfc-url-parser.ts
// File corrected from test-helpers/nfc-parser.ts
import { SumMessage } from '../../types/nfc.types';

/**
 * Helper class for testing NFC URL parsing and verification
 * Simulates the URLs generated by scanning NFC tags
 */
export class NfcUrlParser {
    /**
     * Converts a URL to a SumMessage format
     * @param url - NFC tag URL or parameter string
     * @returns SumMessage object for verification
     */
    static urlToSumMessage(url: string): SumMessage {
        // Determine if the input is a full URL or just parameters
        let queryString = url;
        if (url.includes('?')) {
            queryString = url.split('?')[1];
        }

        // Check if this is a TagTamper type
        const isTagTamper = url.includes('type=tt') || url.includes('ts=');

        return {
            type: isTagTamper ? 'tagtt' : 'tag',
            data: queryString
        };
    }

    /**
     * Generates a test request payload with optional geolocation
     * @param tagParams - URL parameters for the tag
     * @param includeLocation - Whether to include geolocation data
     * @returns Request object ready for testing
     */
    static generateTestRequest(tagParams: Record<string, string>, includeLocation = false): any {
        // Convert parameters to URL query format
        const queryString = Object.entries(tagParams)
            .map(([key, value]) => `${key}=${encodeURIComponent(value)}`)
            .join('&');

        // Determine if this is a TagTamper type
        const isTagTamper = tagParams.type === 'tt' || tagParams.ts !== undefined;

        const request: any = {
            sumMessage: {
                type: isTagTamper ? 'tagtt' : 'tag',
                data: queryString
            }
        };

        // Add geolocation if requested
        if (includeLocation) {
            request.geoLocation = {
                latitude: 40.7128, // New York coordinates
                longitude: -74.0060
            };
        }

        return request;
    }

    /**
     * Provides standard test cases for various tag types
     * Used for data-driven testing
     * @returns Array of test cases with URLs and expected results
     */
    static getStandardTestCases(): Array<{
        name: string;
        url: string;
        expectedTagId: string;
        expectedTagType: string;
    }> {
        return [
            {
                name: 'Standard NTAG 424 DNA',
                url: 'https://adaki.me/v?picc=E2347894F792312B&cmac=D3A2910582F48A15&uid=041E3C8A556480',
                expectedTagId: 'ntag424-e2347894',
                expectedTagType: 'NTAG 424 DNA'
            },
            {
                name: 'Encrypted NTAG 424 DNA',
                url: 'https://adaki.me/v?picc=E2347894F792312B&enc=A6B71CC347283FD89ACE1F73D0C53BC4&cmac=F9A7511E3C41A8B7&uid=041E3C8A556480',
                expectedTagId: 'ntag424-e2347894',
                expectedTagType: 'NTAG 424 DNA'
            },
            {
                name: 'NTAG 424 DNA TagTamper (intact)',
                url: 'https://adaki.me/v?type=tt&picc=F1A53D8B62C70E94&enc=D3F57B8A1C649E230A5F7D1862B4F3C5&cmac=8A41D56F3E72C109&uid=04FB52C2496C81',
                expectedTagId: 'tamper-f1a53d8b',
                expectedTagType: 'NTAG 424 DNA TagTamper'
            },
            {
                name: 'NTAG 424 DNA TagTamper (tampered)',
                url: 'https://adaki.me/v?type=tt&picc=F1A53D8B62C70E94&enc=D3F57B8A1C649E230A5F7D1862B4F3C5&cmac=8A41D56F3E72C109&uid=04FB52C2496C81&ts=1',
                expectedTagId: 'tamper-f1a53d8b',
                expectedTagType: 'NTAG 424 DNA TagTamper'
            }
        ];
    }

    /**
     * Generates parameters for performance testing
     * @param count - Number of test cases to generate
     * @returns Array of test parameters
     */
    static generatePerformanceTestCases(count: number): Array<Record<string, string>> {
        const testCases: Array<Record<string, string>> = [];

        for (let i = 0; i < count; i++) {
            // Generate unique PICC and CMAC for each test
            const piccData = this.generateRandomHex(16);
            const cmac = this.generateRandomHex(16);
            const uid = this.generateRandomHex(14);

            testCases.push({
                picc: piccData,
                cmac: cmac,
                uid: uid
            });
        }

        return testCases;
    }

    /**
     * Generates random hexadecimal string of specified length
     * @param length - Desired length of hex string
     * @returns Random hexadecimal string
     */
    private static generateRandomHex(length: number): string {
        let result = '';
        const characters = '0123456789ABCDEF';

        for (let i = 0; i < length; i++) {
            result += characters.charAt(Math.floor(Math.random() * characters.length));
        }

        return result;
    }
}